services:
  # A static site
  - type: web
    name: neotw
    repo: https://github.com/oeyoews/neotw.git
    branch: main
    region: singapore
    env: static
    buildCommand: yarn build:oeyoews
    staticPublishPath: ./dist
    startCommand: yarn install
    plan: starter
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: redirect
        source: /index.html
        destination: /index
      - type: redirect
        source: /main.html
        destination: /main
